name: Build project
concurrency:
  group: ci
  cancel-in-progress: true

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  build:
    name: Build project
    uses: ./.github/workflows/x-build.yml
    secrets: inherit
    permissions:
      contents: write

  publish:
    name: Publish SNAPSHOT version
    needs: build
    uses: ./.github/workflows/x-publish.yml
    secrets: inherit
    with:
      snapshot: true
