name: Publish to Maven Central
on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Publish release
    uses: ./.github/workflows/x-publish.yml
    secrets: inherit
    with:
      snapshot: false
