name: Publish
on:
  workflow_call:
    inputs:
      version:
        description: Version number
        type: string
      snapshot:
        description: Whether this artifact is a snapshot
        type: boolean
        default: true
    secrets:
      GRADLE_ENCRYPTION_KEY:
        required: true
      MAVEN_CENTRAL_USERNAME:
        required: true
      MAVEN_CENTRAL_PASSWORD:
        required: true
      SIGNING_KEY:
        required: true
      SIGNING_KEY_PASSWORD:
        required: true

jobs:
  build:
    name: Build project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Prepare Java & Gradle
        uses: ./.github/actions/prepare-gradle
        with:
          gradle-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
          cache-overwrite-existing: 'true'

      - name: Publish to Maven Central
        run: ./gradlew publishToMavenCentral
        env:
          ORG_GRADLE_PROJECT_VERSION_NAME: ${{ inputs.version }}${{ inputs.snapshot && '-SNAPSHOT' || '' }}
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}

          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_KEY_PASSWORD }}


#      - name: Upload build reports
#        uses: actions/upload-artifact@v7
#        if: always()
#        with:
#          name: build-reports
#          path: '**/build/reports/'
