name: Publish
on:
  workflow_call:
    inputs:
      snapshot:
        description: Whether this artifact is a snapshot
        type: boolean
        default: true
    secrets:
      GRADLE_ENCRYPTION_KEY:
        required: true
      MAVEN_CENTRAL_USERNAME:
        required: true
      MAVEN_CENTRAL_PASSWORD:
        required: true
      SIGNING_KEY:
        required: true
      SIGNING_KEY_PASSWORD:
        required: true

jobs:
  prepare:
    name: Prepare version information
    runs-on: ubuntu-latest
    outputs:
      version-name: ${{ steps.prepare-release-version.outputs.version-name || steps.prepare-snapshot-version.outputs.version-name }}
    steps:
      - name: Prepare release version
        id: prepare-release-version
        if: inputs.snapshot == false
        run: |
          TAG_NAME="${{ github.ref_name }}"
          VERSION_NAME="${TAG_NAME#v}"
          echo "version-name=$VERSION_NAME" >> $GITHUB_OUTPUT

      - name: Prepare snapshot version
        id: prepare-snapshot-version
        if: inputs.snapshot == true
        run: |
          VERSION_NAME="$(date -u '+%Y%m%d')-SNAPSHOT"
          echo "version-name=$VERSION_NAME" >> $GITHUB_OUTPUT
  publish:
    name: Build & publish project
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Prepare Java & Gradle
        uses: ./.github/actions/prepare-gradle
        with:
          gradle-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
          cache-overwrite-existing: 'true'

      - name: Publish to Maven Central
        run: ./gradlew publishToMavenCentral
        env:
          ORG_GRADLE_PROJECT_VERSION_NAME: ${{ needs.prepare.outputs.version-name }}

          ORG_GRADLE_PROJECT_mavenCentralPublishing: 'true'
          ORG_GRADLE_PROJECT_signAllPublications: 'true'

          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}

          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_KEY_PASSWORD }}


#      - name: Upload build reports
#        uses: actions/upload-artifact@v7
#        if: always()
#        with:
#          name: build-reports
#          path: '**/build/reports/'
